<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\AgentForge.Core\AgentForge.Core.csproj" />
    <ProjectReference Include="..\AgentForge.Areas.Abstractions\AgentForge.Areas.Abstractions.csproj" />
    <ProjectReference Include="..\Areas\AgentForge.Areas.Agents\AgentForge.Areas.Agents.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>
</Project>
